name: image_compare
description: A flutter package which makes it easier to display the difference between two images.
version: 2.1.0
homepage: https://github.com/zys0070/ImageCompare

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
